//===- Passes.td - Cinm dialect passes ---------------------*- tablegen -*-===//
//
// This is the definitions file for the Cinm dialect conversion passes.
//
//===----------------------------------------------------------------------===//

#ifndef CINM_CONVERSION_PASSES
#define CINM_CONVERSION_PASSES


include "mlir/Pass/PassBase.td"

//def ConvertCinmToLLVM : ConvertToLlvm<"Cinm", "cinm">;


#endif // CINM_CONVERSION_PASSES