//===- Passes.td - Hbmpim dialect passes ---------------------*- tablegen -*-===//
//
// This is the definitions file for the Hbmpim dialect conversion passes.
//
//===----------------------------------------------------------------------===//

#ifndef HBMPIM_CONVERSION_PASSES
#define HBMPIM_CONVERSION_PASSES

include "mlir/Pass/PassBase.td"



#endif // HBMPIM_CONVERSION_PASSES//===- Passes.td - Hbmpim dialect passes ---------------------*- tablegen -*-===//