// Minimal reproduction of the pattern generated by elementwise tiling when the
// accumulator is itself an ND tensor:
//
//   tensor.empty() : tensor<16384x4xi32>           -- tile scratch
//   <op that writes into it>                        -> tensor<16384x4xi32>
//   tensor.collapse_shape [[0, 1]]                  -> tensor<65536xi32>
//   tensor.collapse_shape %acc [[0, 1]]             -> tensor<16777216xi32>
//   tensor.insert_slice ... into collapsed_acc[%i]  -> tensor<16777216xi32>
//   tensor.expand_shape [[0, 1]]                    -> tensor<8x2097152xi32>
//
// Both collapse_shape / expand_shape pairs are candidates for elimination:
//
//   1. The tile side: tensor.empty -> fill -> collapse -> insert_slice
//      This is the pattern from empty-fill-collapse-insert.mlir.  Handled by
//      the planned eliminate-empty-tensors extension.
//
//   2. The acc side: collapse(%acc) / expand(%updated) around insert_slice
//      Here %acc is an iter_arg whose initial value is tensor.empty().
//      After eliminate-empty-tensors rewrites the outer empty, both
//      collapse(expand(x, R), R) pairs cancel via
//      ComposeReassociativeReshapeOps, leaving a plain insert_slice on the
//      flat tensor with no ND reshape at all.
//
// Try:
//   mlir-opt %s --one-shot-bufferize="bufferize-function-boundaries=true" \
//     --canonicalize -o -

func.func @nd_acc_collapse_insert(
    %val: i32,
    %acc: tensor<8x2097152xi32>,
    %i: index) -> tensor<8x2097152xi32> {

  // Step 1: produce a shaped tile (stand-in for cnm.gather).
  %empty  = tensor.empty() : tensor<16384x4xi32>

  %tile   = linalg.fill ins(%val : i32)
                        outs(%empty : tensor<16384x4xi32>)
            -> tensor<16384x4xi32>

  // Step 2: flatten the tile.
  %flat_tile = tensor.collapse_shape %tile [[0, 1]]
                 : tensor<16384x4xi32> into tensor<65536xi32>

  // Step 3: flatten the ND accumulator.
  %flat_acc = tensor.collapse_shape %acc [[0, 1]]
                : tensor<8x2097152xi32> into tensor<16777216xi32>

  // Step 4: insert the flat tile into the flat accumulator.
  %updated_flat = tensor.insert_slice %flat_tile into %flat_acc[%i] [65536] [1]
                    : tensor<65536xi32> into tensor<16777216xi32>

  // Step 5: expand the accumulator back to its original ND shape.
  %result = tensor.expand_shape %updated_flat [[0, 1]] output_shape [8, 2097152]
              : tensor<16777216xi32> into tensor<8x2097152xi32>

  return %result : tensor<8x2097152xi32>
}

func.func @nd_acc_collapse_insert_after_transform(
    %val: i32,
    %acc: tensor<8x2097152xi32>,
    %i: index) -> tensor<8x2097152xi32> {

  %empty  = tensor.empty() : tensor<16384x4xi32>

  %flat_acc = tensor.collapse_shape %acc [[0, 1]]
                : tensor<8x2097152xi32> into tensor<16777216xi32>

  %tile_out = tensor.extract_slice %flat_acc[%i] [65536] [1]
                    : tensor<16777216xi32> to tensor<65536xi32>

  %tile_expanded = tensor.expand_shape %tile_out [[0, 1]] output_shape [16384, 4]
              : tensor<65536xi32> into tensor<16384x4xi32>


  %tile = linalg.fill ins(%val : i32)
                        outs(%tile_expanded : tensor<16384x4xi32>)
            -> tensor<16384x4xi32>

  %flat_tile = tensor.collapse_shape %tile [[0, 1]]
                 : tensor<16384x4xi32> into tensor<65536xi32>

  // Step 4: insert the flat tile into the flat accumulator.
  %updated_flat = tensor.insert_slice %flat_tile into %flat_acc[%i] [65536] [1]
                    : tensor<65536xi32> into tensor<16777216xi32>

  // Step 5: expand the accumulator back to its original ND shape.
  %result = tensor.expand_shape %updated_flat [[0, 1]] output_shape [8, 2097152]
              : tensor<16777216xi32> into tensor<8x2097152xi32>

  return %result : tensor<8x2097152xi32>
}
