################################################################################
# AlpineIncGen
#
# MLIR Alpine dialect generated includes.
################################################################################

add_custom_target(AlpineIncGen)

# Attributes, Dialect, Operations and Types.
add_subdirectory(IR)
add_subdirectory(Transforms)
