//===- Attributes.td - Cinm dialect attributes --------*- tablegen -*-===//
//
// This is the definitions file for the Cinm dialect attributes.
//
//===----------------------------------------------------------------------===//

#ifndef CINM_ATTRIBUTES
#define CINM_ATTRIBUTES

include "cinm-mlir/Dialect/Cinm/IR/CinmAttributesBase.td"
include "cinm-mlir/Dialect/Cinm/IR/CinmAttributesForOps.td"
include "cinm-mlir/Dialect/Cinm/IR/CinmPlatformAttrInterface.td"

#endif
