//===- Attributes.td - ${dialectNameUpper} dialect attributes --------*- tablegen -*-===//
//
// This is the definitions file for the ${dialectNameUpper} dialect attributes.
//
//===----------------------------------------------------------------------===//

#ifndef ${dialectNameAllCaps}_ATTRIBUTES
#define ${dialectNameAllCaps}_ATTRIBUTES

include "${projectPrefix}/Dialect/${dialectNameUpper}/IR/${dialectNameUpper}Base.td"

#endif
